name: " PR Label Checker"
on:
  pull_request:
    branches:
      - "**"
      - "!master"
    types:
      - reopened
      - labeled
      - unlabeled
jobs:
  add_comment:
    name: "Check PR Labels"
    runs-on: ubuntu-latest
    steps:
      - uses: andyantrim/label_checker_actions@v0.1
        with:
          labels: "major,minor,patch"
