name: " PR Open"
on:
  pull_request:
    branches:
      - "**"
      - "!master"
    types:
      - opened
jobs:
  add_comment:
    name: "Add Comment"
    runs-on: ubuntu-latest
    steps:
      - uses: mshick/add-pr-comment@v1
        with:
          message: Set a versoning laben to the pull request.
